vich_uploader:
    db_driver: orm

    mappings:
        user_thumbnail:
            uri_prefix: /uploads/users
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        card_thumbnail:
            uri_prefix: /uploads/cards
            upload_destination: '%kernel.project_dir%/public/uploads/cards'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        collection_thumbnail:
            uri_prefix: /uploads/collections
            upload_destination: '%kernel.project_dir%/public/uploads/collections'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
