controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

api_logout:
    path: /api/logout

request_password_reset:
    path: /request-password-reset
    controller: App\Controller\PasswordResetController::requestPasswordReset
